# Generated by Django 4.2.10 on 2026-04-02 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(help_text='City, State or Region', max_length=255)),
                ('date_of_birth', models.DateField()),
                ('last_donation_date', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Donor is available for donation')),
                ('wallet_address', models.CharField(blank=True, help_text='Blockchain wallet address for token rewards', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blood_type'], name='donor_donor_blood_t_e8f0f8_idx'), models.Index(fields=['is_available'], name='donor_donor_is_avai_e0de41_idx'), models.Index(fields=['location'], name='donor_donor_locatio_5c0574_idx')],
            },
        ),
    ]
