# Generated by Django 4.2.10 on 2026-04-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True)),
                ('criteria', models.CharField(max_length=255)),
                ('points_reward', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('available_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='donor.donor')),
            ],
            options={
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points_cost', models.IntegerField()),
                ('quantity_available', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('redemption_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='donor.donor')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.reward')),
            ],
            options={
                'ordering': ['-redemption_date'],
            },
        ),
        migrations.CreateModel(
            name='RewardToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Amount of tokens issued')),
                ('transaction_hash', models.CharField(help_text='Blockchain transaction hash', max_length=255)),
                ('reward_type', models.CharField(choices=[('donation_reward', 'Donation Reward'), ('referral_bonus', 'Referral Bonus'), ('achievement_reward', 'Achievement Reward'), ('participation_bonus', 'Participation Bonus')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_tokens', to='donor.donor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['donor'], name='rewards_rew_donor_i_b39a01_idx'), models.Index(fields=['created_at'], name='rewards_rew_created_98a93f_idx'), models.Index(fields=['transaction_hash'], name='rewards_rew_transac_3cecd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_amount', models.IntegerField()),
                ('source', models.CharField(choices=[('donation', 'Blood Donation'), ('badge', 'Badge Achievement'), ('referral', 'Referral'), ('participation', 'Event Participation'), ('admin_award', 'Admin Award'), ('redemption', 'Redemption')], max_length=30)),
                ('description', models.TextField()),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.points')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='rewards_poi_created_f7f74d_idx'), models.Index(fields=['source'], name='rewards_poi_source_38dd4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DonorBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.badge')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='donor.donor')),
            ],
            options={
                'ordering': ['-earned_date'],
                'unique_together': {('donor', 'badge')},
            },
        ),
    ]
