# Generated by Django 4.2.10 on 2026-04-02 09:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='scheduled', max_length=20)),
                ('blood_units', models.DecimalField(decimal_places=2, default=0.45, max_digits=5)),
                ('blockchain_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donor.donor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_donations', to='hospital.hospital')),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('collected_at', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('testing', 'Testing'), ('storage', 'Storage'), ('transfused', 'Transfused'), ('expired', 'Expired')], default='collected', max_length=20)),
                ('hiv_test', models.BooleanField(default=False)),
                ('hepatitis_test', models.BooleanField(default=False)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Ethereum transaction hash', max_length=256, null=True)),
                ('status_history', models.JSONField(blank=True, default=list, help_text='Status change history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units_inventory', to='hospital.hospital')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_units', to='donor.donor')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['blood_type'], name='blood_track_blood_t_d5b27c_idx'), models.Index(fields=['status'], name='blood_track_status_49648c_idx'), models.Index(fields=['donor', 'collected_at'], name='blood_track_donor_i_6c0548_idx'), models.Index(fields=['current_hospital', 'status'], name='blood_track_current_748cb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='BloodTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('hospital_to_hospital', 'Hospital to Hospital'), ('hospital_to_patient', 'Hospital to Patient'), ('bank_to_hospital', 'Bank to Hospital')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('transfer_date', models.DateTimeField()),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='blood_tracking.blooddonation')),
                ('from_hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfers', to='hospital.hospital')),
                ('to_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='hospital.hospital')),
            ],
            options={
                'ordering': ['-transfer_date'],
                'indexes': [models.Index(fields=['status', 'transfer_date'], name='blood_track_status_b404aa_idx'), models.Index(fields=['from_hospital', 'transfer_date'], name='blood_track_from_ho_55c345_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='blooddonation',
            index=models.Index(fields=['donor', 'donation_date'], name='blood_track_donor_i_ecc73f_idx'),
        ),
        migrations.AddIndex(
            model_name='blooddonation',
            index=models.Index(fields=['hospital', 'donation_date'], name='blood_track_hospita_b567f1_idx'),
        ),
        migrations.AddIndex(
            model_name='blooddonation',
            index=models.Index(fields=['status'], name='blood_track_status_8a4d0a_idx'),
        ),
    ]
