# Generated by Django 4.2.10 on 2026-04-02 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('donation_requests', models.BooleanField(default=True)),
                ('blood_availability', models.BooleanField(default=True)),
                ('transfer_updates', models.BooleanField(default=True)),
                ('reward_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('emergency_alert', 'Emergency Alert'), ('donation_reminder', 'Donation Reminder'), ('request_fulfilled', 'Request Fulfilled'), ('donation_request', 'Donation Request'), ('donation_scheduled', 'Donation Scheduled'), ('blood_available', 'Blood Available'), ('blood_needed', 'Blood Needed'), ('transfer_update', 'Transfer Update'), ('reward', 'Reward'), ('system', 'System')], max_length=30)),
                ('message', models.TextField()),
                ('blood_type', models.CharField(blank=True, help_text='Blood type for emergency alerts', max_length=3, null=True)),
                ('location', models.CharField(blank=True, help_text='Location for emergency alerts', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
